#!/bin/bash
# 20220427
# han
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export 'NLS_LANG=american_america.AL32UTF8'


#color level
SETCOLOR_SUCCESS="echo -en \\033[1;32m"
SETCOLOR_FAILURE="echo -en \\033[1;31m"
SETCOLOR_WARNING="echo -en \\033[1;33m"
SETCOLOR_NORMAL="echo -en \\033[0;39m"


# 定义一堆时间变量,方便调用
# shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
today_d8=$(date +%Y%m%d)
# shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
today_now_d14=$(date +%Y%m%d%H%M%S)
# shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
today_now_sec=$(date +%s)
# shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
today_begin_d14=$(date -d "$(date +%F)" +%Y%m%d%H%M%S) || true
# shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
today_begin_sec=$(date -d "$(date +%F)" +%s) || true

# shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
yestertoday_d8=$(date -d "-1 day $(date +%F)" +%Y%m%d) || true
# shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
yestertoday_now_d14=$(date +%Y%m%d%H%M%S -d "-1 day")
# shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
yestertoday_now_sec=$(date +%s -d "-1 day")
# shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
yestertoday_begin_d14=$(date -d "-1 day $(date +%F)" +%Y%m%d%H%M%S) || true
# shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
yestertoday_begin_sec=$(date -d "-1 day $(date +%F)" +%s) || true


# 所有日志函数返回值都是0, 执行日志函数的结果必为成功. 但是打印到屏幕是分为stdout和stderr的

function LOGMSG() # 打印日志: 信息级别, stdout
{
    OLDIFS=${IFS}
    IFS=$' \t\n'
    time=$(date "+[%F %T]")
    echo -e "${time}\tINFO\t$*"
    ${SETCOLOR_NORMAL}
    # shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
    [[ -f "${log_file}" ]] && echo -e "${time}\tINFO\t$*" >> "${log_file}"
    IFS=${OLDIFS}
    return 0
}

function LOGWARNMSG() # 打印日志: 警告级别, stderr
{
    OLDIFS=${IFS}
    IFS=$' \t\n'
    time=$(date "+[%F %T]")
    ${SETCOLOR_WARNING}
    echo -e "${time}\tWARN\t$*" >&2
    ${SETCOLOR_NORMAL}
    # shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
    if [[ -f "${log_err}" ]]
    then
            echo -e "${time}\tWARN\t$*" >> "${log_err}"
    fi
    if [[ -f "${log_file}" ]]
    then
            echo -e "${time}\tWARN\t$*" >> "${log_file}"
    fi
    IFS=${OLDIFS}
    return 0
}

function LOGSUCMSG() # 打印日志: 成功级别, stdout
{
    OLDIFS=${IFS}
    IFS=$' \t\n'
    time=$(date "+[%F %T]")
    ${SETCOLOR_SUCCESS}
    echo -e "${time}\tSUCCESS\t$*"
    ${SETCOLOR_NORMAL}
    [[ -f "${log_file}" ]] && echo -e "${time}\tSUCCESS\t$*" >> "${log_file}"
    IFS=${OLDIFS}
    return 0
}

function LOGERRORMSG() # 打印日志: 失败级别, stderr
{
    OLDIFS=${IFS}
    IFS=$' \t\n'
    time=$(date "+[%F %T]")
    ${SETCOLOR_FAILURE}
    echo -e "${time}\tERROR\t$*" >&2
    ${SETCOLOR_NORMAL}
    if [[ -f "${log_err}" ]]
    then
            echo -e "${time}\tERROR\t$*" >> "${log_err}"
    fi
    if [[ -f "${log_file}" ]]
    then
            echo -e "${time}\tERROR\t$*" >> "${log_file}"
    fi
    IFS=${OLDIFS}
    return 0
}


function read_conf() # 读取section、keyword形式的配置文件 read_conf conf_file section key
{
    self_sect=$2;self_conf=$1;self_key=$3
    temp_conf=$(grep -vE "^$|^#" "${self_conf}" | sed -n "/\[${self_sect}\]/I,/\[/p" | sed "/^\[/d")
    self_result=$(echo "${temp_conf}" | grep -iw "${self_key}" | cut -d= -f2 | tail -n1)
    # shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
    eval "$(echo "${self_key}"="${self_result}")"
}

function read_conf_section() # 读取section、keyword形式的配置文件并将整个section的所有k-v都声明出来 read_conf conf_file section
{
  OLDIFS=${IFS}
  IFS=$'\n'
  self_sect=$2;self_conf=$1
  temp_conf=$(grep -v ^# "$self_conf"|grep -v "^$"|sed -n "/\[${self_sect}\]/I,/^\[/p"|sed "/^\[/d")
  for line in ${temp_conf}
  do
    #echo $line
    eval "${line}"
  done
  IFS=${OLDIFS}
}

function getSections(){ # 读取ini文件所有的sections ,参数个数 1,参数 1 :ini 文件名
    if [[ -f "$1" ]];then
        sections=$(grep  -Po '(?<=\[).*(?=\])' "$1")
        echo "${sections}"
    else
        echo "$1":配置文件不存在
    fi
}

function check_var() { # 如果变量2不在环境变量里,就读配置文件,如果配置文件也没有就报错退出
    # shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
    key=$(eval echo $(echo "$"$2))
    # shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
    [[ "" == "${key}" ]] && read_conf "${conf_file}" "$1" "$2"
    # shellcheck disable=SC1090,SC1091,SC2034,SC2046,SC2086,SC2116,SC2154
    key=$(eval echo $(echo "$"$2))
    [[ "" == "${key}" ]] && LOGERRORMSG "$2 变量为空，请检查配置文件。 " && exit 3
    unset key
}

function quota_cpu() { # 限制CPU使用率, 使用方法: quota_cpu 限定使用的核数, 注意调用该函数的脚本在执行完成后需自行删除 ${pdir} cgdelete -r cpu,cpuacct:${script_name}
    if ! (ls /sys/fs/cgroup/cpu,cpuacct &>/dev/null); then
        LOGERRORMSG "该机器未安装cgroup, 无法控制cpu使用率"
        return
    fi
    local quota=$1
    local script_name
    script_name=$(basename "$0")
    local pid=$$
    local period_us=100000
    local quota_us
    quota_us=$(echo "scale=0;${period_us}"*"${quota}/1" | bc)
    pdir=/sys/fs/cgroup/cpu,cpuacct/${script_name}
    mkdir -p "${pdir}"
    echo "${pid}" > "${pdir}"/cgroup.procs
    echo "${period_us}" > "${pdir}"/cpu.cfs_period_us
    echo "${quota_us}" > "${pdir}"/cpu.cfs_quota_us
}
